firstapp/urls.py
from django.urls import path 
from firstapp.views import index,PostCreate,detail
from django.conf.urls.static import static
from django.conf import settings
app_name="firstapp"
urlpatterns = [
    path('',index,name='index'),
    path('create/',PostCreate.as_view(),name='create'),
    path('detail/<int:pk>/',detail,name='detail'),
    
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('account/',include('registration.backends.default.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User
class Timestamp(models.Model):
     created_at=models.DateTimeField(auto_now_add=True)
     updated_at=models.DateTimeField(auto_now=True)
     user=models.ForeignKey(User,on_delete=models.CASCADE)
     class Meta:
        abstract=True
class Post(Timestamp):
    title=models.CharField(max_length=100)
    description=models.TextField()
    image=models.ImageField(upload_to='')
    likes=models.IntegerField(default=0)
    def __str__(self):
        return self.title

class Comment(Timestamp):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    comment=models.TextField()
    def __str__(self):
        return self.comment 

firstapp/forms.py
from django import forms
from firstapp.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['comment']

firstapp/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse,HttpRequest
from firstapp.models import Post,Comment
from django.views.generic.edit import CreateView
from firstapp.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
def index(request):
	# process the data
	posts = Post.objects.all()
	context = {'posts':posts}
	return render(request,'index.html',context)

class PostCreate(LoginRequiredMixin,CreateView):
	model = Post
	fields = ['title','description','image']
	template_name = 'create.html'
	success_url = '/'

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)


@login_required
def detail(request,pk):
    p = Post.objects.get(pk = pk)
    comments = Comment.objects.filter(post_id = pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            comment = form.cleaned_data['comment']
            c = Comment(post_id = pk,comment = comment,user = request.user)
            c.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('firstapp:detail', kwargs = {'pk':pk}))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()

    return render(request, 'detail.html', {'form': form,'p':p,'comments':comments})

firstapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">ArT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'firstapp:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'firstapp:create' %}">Post</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          {% if not user.is_authenticated %}

          <a  class="btn btn-primary" href="{% url 'auth_login' %}">login</a>
          <a  class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
          {% else %}
          <a  class="btn btn-outline" href="{% url 'auth_logout' %}">logout</a>
          {% endif %}

        </div>
      </nav>
      <div class="container">
        <br>
      {%block content%}
      
      {%endblock%}
      </div >


      

firstapp/templates/create.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    
    <input class="btn btn-primary" type="submit" value="Save">
</form>
{% endblock %}

firstapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<div class="col-6">

	<span id="title">{{p.title}}</span><br>
	{{p.description}}<br>
	<img src="{{p.image.url}}" width="300" height="300"><br>
	
	</div>

	<div class="col-6">

	<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
	</form>

	</div>

</div>
	<br><br><br>
	<h6>Comments:</h6>
    
    {% for i in comments %}

    {{forloop.counter}} - {{i.comment}} <br>
    at {{i.created_at}} by {{i.user}} <br>

    {% endfor %}

</div>

{% endblock %}

firstapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'firstapp:detail' post.id %}">{{ post.title }}</a></h5>
                    <p class="card-text">{{ post.description }}</p>
                    <p class="card-text">
                        <small class="text-muted">
                            {{ post.created_at|date:"F d, Y" }} by{{ post.user.username }}
                        </small>
                    </p>
                
                </div>
            </div>

        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}